# Generated by Django 5.2.9 on 2025-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ORD-00000000-0000', editable=False, max_length=20, unique=True),
        ),
    ]
