# Generated by Django 5.2.9 on 2025-12-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menuitem_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject_type', models.CharField(choices=[('order_inquiry', 'Order Inquiry'), ('general_question', 'General Question'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('other', 'Other')], max_length=20)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='orders_cont_created_f5ab0a_idx'), models.Index(fields=['status'], name='orders_cont_status_ca8369_idx'), models.Index(fields=['email'], name='orders_cont_email_a09f2b_idx'), models.Index(fields=['name'], name='orders_cont_name_7cb5a1_idx')],
            },
        ),
    ]
